# Generated by Django 4.0 on 2022-01-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=10)),
                ('passwords', models.CharField(max_length=50)),
                ('titles', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
