# Generated by Django 4.0 on 2022-01-06 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='visitcount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
