# Generated by Django 4.0 on 2022-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0002_post_postdate_post_visitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visitcount',
            field=models.IntegerField(default=0),
        ),
    ]
